/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.Cliente;
import repositorios.RegistroDeVendas;

/**
 *
 * @author USER
 */
public class Buscas extends javax.swing.JFrame {

    /**
     * Creates new form Buscas
     */
    public Buscas() {
        initComponents();
    }
private RegistroDeVendas registroDeVendas = new RegistroDeVendas(); 

    public RegistroDeVendas getRegistroDeVendas() {
        return registroDeVendas;
    }

    public void setRegistroDeVendas(RegistroDeVendas registroDeVendas) {
        this.registroDeVendas = registroDeVendas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonSairCalcado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldClienteNomeBuscas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaClienteBuscas = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldClienteCpfBuscas = new javax.swing.JTextField();
        jButtonConsultaClientePorNome = new javax.swing.JButton();
        jButtonConsultaClientePorCpfBuscas = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldVendedorNomeBusca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaVendedoresBuscas = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldVendedorCpfBuscas = new javax.swing.JTextField();
        jButtonNomeVendedor = new javax.swing.JButton();
        jButtonCpfVendedor = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTextFieldCodigoCalcadoBuscas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCalcados = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldModeloCalcadoBuscas = new javax.swing.JTextField();
        jButtonCodigoCalcadoBuscas = new javax.swing.JButton();
        jButtonModeloCalcadoBuscas = new javax.swing.JButton();

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Calçados"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jButtonSairCalcado.setBackground(new java.awt.Color(255, 0, 51));
        jButtonSairCalcado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSairCalcado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSairCalcado.setText("X");
        jButtonSairCalcado.setBorder(null);
        jButtonSairCalcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCalcadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSairCalcado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonSairCalcado)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTextFieldClienteNomeBuscas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteNomeBuscasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome:");

        jTextAreaClienteBuscas.setColumns(20);
        jTextAreaClienteBuscas.setRows(5);
        jScrollPane2.setViewportView(jTextAreaClienteBuscas);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("CPF:");

        jButtonConsultaClientePorNome.setBackground(new java.awt.Color(0, 153, 255));
        jButtonConsultaClientePorNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonConsultaClientePorNome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultaClientePorNome.setText("Nome");
        jButtonConsultaClientePorNome.setBorder(null);
        jButtonConsultaClientePorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaClientePorNomeActionPerformed(evt);
            }
        });

        jButtonConsultaClientePorCpfBuscas.setBackground(new java.awt.Color(0, 153, 255));
        jButtonConsultaClientePorCpfBuscas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonConsultaClientePorCpfBuscas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultaClientePorCpfBuscas.setText("CPF");
        jButtonConsultaClientePorCpfBuscas.setBorder(null);
        jButtonConsultaClientePorCpfBuscas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaClientePorCpfBuscasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jTextFieldClienteNomeBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldClienteCpfBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConsultaClientePorCpfBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConsultaClientePorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClienteNomeBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldClienteCpfBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultaClientePorNome)
                    .addComponent(jButtonConsultaClientePorCpfBuscas))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTextFieldVendedorNomeBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVendedorNomeBuscaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nome:");

        jTextAreaVendedoresBuscas.setColumns(20);
        jTextAreaVendedoresBuscas.setRows(5);
        jScrollPane3.setViewportView(jTextAreaVendedoresBuscas);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("CPF:");

        jButtonNomeVendedor.setBackground(new java.awt.Color(0, 153, 255));
        jButtonNomeVendedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNomeVendedor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNomeVendedor.setText("Nome");
        jButtonNomeVendedor.setBorder(null);
        jButtonNomeVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNomeVendedorActionPerformed(evt);
            }
        });

        jButtonCpfVendedor.setBackground(new java.awt.Color(0, 153, 255));
        jButtonCpfVendedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCpfVendedor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCpfVendedor.setText("CPF");
        jButtonCpfVendedor.setBorder(null);
        jButtonCpfVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCpfVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jTextFieldVendedorNomeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldVendedorCpfBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVendedorNomeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldVendedorCpfBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCpfVendedor)
                    .addComponent(jButtonNomeVendedor))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calçados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Modelo:");

        jTextAreaCalcados.setColumns(20);
        jTextAreaCalcados.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCalcados);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Código:");

        jButtonCodigoCalcadoBuscas.setBackground(new java.awt.Color(0, 153, 255));
        jButtonCodigoCalcadoBuscas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCodigoCalcadoBuscas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCodigoCalcadoBuscas.setText("Código");
        jButtonCodigoCalcadoBuscas.setBorder(null);
        jButtonCodigoCalcadoBuscas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCodigoCalcadoBuscasActionPerformed(evt);
            }
        });

        jButtonModeloCalcadoBuscas.setBackground(new java.awt.Color(0, 153, 255));
        jButtonModeloCalcadoBuscas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonModeloCalcadoBuscas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModeloCalcadoBuscas.setText("Modelo");
        jButtonModeloCalcadoBuscas.setBorder(null);
        jButtonModeloCalcadoBuscas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModeloCalcadoBuscasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jTextFieldModeloCalcadoBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCodigoCalcadoBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCodigoCalcadoBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModeloCalcadoBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldModeloCalcadoBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCodigoCalcadoBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModeloCalcadoBuscas)
                    .addComponent(jButtonCodigoCalcadoBuscas))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldClienteNomeBuscasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteNomeBuscasActionPerformed
        
    }//GEN-LAST:event_jTextFieldClienteNomeBuscasActionPerformed

    private void jButtonCodigoCalcadoBuscasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCodigoCalcadoBuscasActionPerformed
        this.consultaCalcadoPorCodigo();
    }//GEN-LAST:event_jButtonCodigoCalcadoBuscasActionPerformed

    private void jButtonModeloCalcadoBuscasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModeloCalcadoBuscasActionPerformed
        this.consultaCalcadoPorModelo();
    }//GEN-LAST:event_jButtonModeloCalcadoBuscasActionPerformed

    private void jButtonConsultaClientePorCpfBuscasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaClientePorCpfBuscasActionPerformed
        this.consultaClientePorCpf();
    }//GEN-LAST:event_jButtonConsultaClientePorCpfBuscasActionPerformed

    private void jTextFieldVendedorNomeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVendedorNomeBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVendedorNomeBuscaActionPerformed

    private void jButtonConsultaClientePorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaClientePorNomeActionPerformed
      
        this.consultaClientePorNome();
    }//GEN-LAST:event_jButtonConsultaClientePorNomeActionPerformed

    private void jButtonSairCalcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCalcadoActionPerformed
        this.sair();
    }//GEN-LAST:event_jButtonSairCalcadoActionPerformed

    private void jButtonNomeVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNomeVendedorActionPerformed
        this.consultaVendedorPorNome();
    }//GEN-LAST:event_jButtonNomeVendedorActionPerformed

    private void jButtonCpfVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCpfVendedorActionPerformed
        this.consultaVendedorPorCpf();
    }//GEN-LAST:event_jButtonCpfVendedorActionPerformed

    private void sair(){
        this.dispose();
    }
     private void consultaCalcadoPorCodigo(){
       jTextAreaCalcados.setText("");
        String output="";
        int contador=0;
      for(int i=0;i<registroDeVendas.getCalcados().size();i++){
          if(this.registroDeVendas.getCalcados().get(i).getCodigoDoProduto().equals(this.jTextFieldCodigoCalcadoBuscas.getText())){
              contador++;
              output+="Resultado nº "+ contador+"\n";
              output += registroDeVendas.getCalcados().get(i).toString();
              
          }
      }
      this.jTextAreaCalcados.setText(output);

    }
    private void consultaCalcadoPorModelo(){
       jTextAreaCalcados.setText("");
        String output="";
        int contador=0;
      for(int i=0;i<registroDeVendas.getCalcados().size();i++){
          if(this.registroDeVendas.getCalcados().get(i).getModelo().equals(this.jTextFieldModeloCalcadoBuscas.getText())){
              contador++;
              output+="Resultado nº "+ contador+"\n";
              output += registroDeVendas.getCalcados().get(i).toString();
              
          }
      }
      this.jTextAreaCalcados.setText(output);

    }
    
    private void consultaVendedorPorNome(){
       jTextAreaVendedoresBuscas.setText("");
        String output="";
        int contador=0;
      for(int i=0;i<registroDeVendas.getVendedores().size();i++){
          if(this.registroDeVendas.getVendedores().get(i).getNome().equals(this.jTextFieldVendedorNomeBusca.getText())){
              contador++;
              output+="Resultado nº "+ contador+"\n";
              output += registroDeVendas.getVendedores().get(i).toString();
              
          }
      }
      this.jTextAreaVendedoresBuscas.setText(output);

    }
     private void consultaVendedorPorCpf(){
       jTextAreaVendedoresBuscas.setText("");
        String output="";
        int contador=0;
      for(int i=0;i<registroDeVendas.getVendedores().size();i++){
          if(this.registroDeVendas.getVendedores().get(i).getCpf().equals(this.jTextFieldVendedorCpfBuscas.getText())){
              contador++;
              output+="Resultado nº "+ contador+"\n";
              output += registroDeVendas.getVendedores().get(i).toString();
              
          }
      }
      this.jTextAreaVendedoresBuscas.setText(output);

    }
    
    private void consultaClientePorNome(){
       jTextAreaClienteBuscas.setText("");
        String output="";
        int contador=0;
      for(int i=0;i<registroDeVendas.getClientes().size();i++){
          if(this.registroDeVendas.getClientes().get(i).getNome().equals(this.jTextFieldClienteNomeBuscas.getText())){
              contador++;
              output+="Resultado nº "+ contador+"\n";
              output += registroDeVendas.getClientes().get(i).toString();
              
          }
      }
      this.jTextAreaClienteBuscas.setText(output);

    }
   
    private void consultaClientePorCpf(){
       jTextAreaClienteBuscas.setText("");
        String output="";
        int contador=0;
      for(int i=0;i<registroDeVendas.getClientes().size();i++){
          if(this.registroDeVendas.getClientes().get(i).getCpf().equals(this.jTextFieldClienteCpfBuscas.getText())){
              contador++;
              output+="Resultado nº "+ contador+"\n";
              output += registroDeVendas.getClientes().get(i).toString();
              
          }
      }
      this.jTextAreaClienteBuscas.setText(output);

    }
    
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCodigoCalcadoBuscas;
    private javax.swing.JButton jButtonConsultaClientePorCpfBuscas;
    private javax.swing.JButton jButtonConsultaClientePorNome;
    private javax.swing.JButton jButtonCpfVendedor;
    private javax.swing.JButton jButtonModeloCalcadoBuscas;
    private javax.swing.JButton jButtonNomeVendedor;
    private javax.swing.JButton jButtonSairCalcado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaCalcados;
    private javax.swing.JTextArea jTextAreaClienteBuscas;
    private javax.swing.JTextArea jTextAreaVendedoresBuscas;
    private javax.swing.JTextField jTextFieldClienteCpfBuscas;
    private javax.swing.JTextField jTextFieldClienteNomeBuscas;
    private javax.swing.JTextField jTextFieldCodigoCalcadoBuscas;
    private javax.swing.JTextField jTextFieldModeloCalcadoBuscas;
    private javax.swing.JTextField jTextFieldVendedorCpfBuscas;
    private javax.swing.JTextField jTextFieldVendedorNomeBusca;
    // End of variables declaration//GEN-END:variables
}
